# Generated by Django 5.0.4 on 2024-05-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_grade_grade_alter_course_teacher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeTranslation',
        ),
    ]
