# Generated by Django 5.0.4 on 2024-05-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_delete_gradetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оцінка'),
        ),
    ]
