# Generated by Django 5.0.4 on 2024-05-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Запис на курс', 'verbose_name_plural': 'Записи на курси'},
        ),
        migrations.AlterField(
            model_name='coursetranslation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Name of the course'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('course', 'student')},
        ),
    ]
