# Generated by Django 5.0.4 on 2024-05-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Студент'), ('teacher', 'Викладач')], max_length=10, null=True, verbose_name='Роль користувача'),
        ),
    ]
