# Generated by Django 5.0.4 on 2024-05-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_profile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курси'},
        ),
        migrations.AlterModelOptions(
            name='coursetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Курс Translation'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Оцінка', 'verbose_name_plural': 'Оцінки'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Заняття', 'verbose_name_plural': 'Заняття'},
        ),
        migrations.AlterModelOptions(
            name='lessontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Заняття Translation'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
    ]
